// <auto-generated />
using System;
using GameBacklog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameBacklog.Api.Migrations
{
    [DbContext(typeof(GameBacklogDbContext))]
    [Migration("20260830213711_CreateCatalogAndBacklog")]
    partial class CreateCatalogAndBacklog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GameBacklog.Api.Models.BacklogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogGameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogGameId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("BacklogEntries");
                });

            modelBuilder.Entity("GameBacklog.Api.Models.CatalogGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MetadataFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawgUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleasedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RawgId")
                        .IsUnique();

                    b.ToTable("CatalogGames");
                });

            modelBuilder.Entity("GameBacklog.Api.Models.BacklogEntry", b =>
                {
                    b.HasOne("GameBacklog.Api.Models.CatalogGame", "CatalogGame")
                        .WithOne("BacklogEntry")
                        .HasForeignKey("GameBacklog.Api.Models.BacklogEntry", "CatalogGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogGame");
                });

            modelBuilder.Entity("GameBacklog.Api.Models.CatalogGame", b =>
                {
                    b.Navigation("BacklogEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
